all: False
template: testify
filename: '{{base (trimSuffix ".go" .InterfaceFile)}}_mock.go'
packages:
  github.com/imkk000/task/v3/internal/fingerprint:
    interfaces:
      SourcesCheckable:
      StatusCheckable:
